### ISSUE TITLE
Update github actions only once a month

### ISSUE THREAD

**Issue by notFloran** [Akollade/renovate-config#7]
To avoid spam every week end

**Comment by nclsHart** [comment]
Even with this spam, projects are not fully updated, there is still some packages waiting.

I don't know if doing this once per month could be a solution.

First, we could move this during week days to avoid week-end. For example during monday or friday.
And once per two weeks could be an intermediate value.

**Comment by nclsHart** [comment]
Sorry my bad, I've read title to quickly.

Ok for updating github actions once per month.
